version: "3.4"

services:
  db:
    build:
      context: ./deploy/db
    ports:
      - 5432:5432
    networks:
      - stroytorg-network

  api:
    build:
      context: ./src
      dockerfile: Stroytorg.Host/Dockerfile
    depends_on:
      - db
    networks:
      - stroytorg-network

  frontend:
    build:
      context: ./src/Stroytorg.App
    ports:
      - 4200:80
    depends_on:
      - api
    networks:
      - stroytorg-network

  router:
    build:
      context: ./deploy/router
    ports:
      - 80:80
    depends_on:
      - api
      - frontend
    networks:
      - stroytorg-network

networks:
  stroytorg-network:
    driver: bridge
