version: '3.4'

services:
  api:
    build:
      context: ./src
      dockerfile: Stroytorg.Host/Dockerfile
    depends_on:
      - db
    
  frontend:
    build:
      context: ./src/Stroytorg.App
      dockerfile: Dockerfile
    depends_on:
      - api
  
  db:
    build:
      context: ./deploy/db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"

  router:
     build:
       context: ./deploy/router
       dockerfile: Dockerfile
     ports:
       - 80:80
     depends_on:
       - api
       - frontend