name: Backend CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./Stroytorg.API

      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./Stroytorg.API

      - name: Run tests
        run: dotnet test --configuration Release --no-build
        working-directory: ./Stroytorg.API