name: Frontend CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./src/Stroytorg.App

      - name: Build Angular app
        run: npm run build
        working-directory: ./src/Stroytorg.App